# Generated by Django 4.2.3 on 2023-08-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='timestamp',
        ),
    ]
