# Generated by Django 4.2.3 on 2023-08-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_remove_contactmessage_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
