# Generated by Django 4.2.3 on 2023-08-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0007_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='user_appointments',
            name='appointment_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
