# Generated by Django 4.2.3 on 2023-08-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0008_delete_service_user_appointments_appointment_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all_appointment',
        ),
        migrations.RemoveField(
            model_name='user_appointments',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_appointments',
            name='appointment_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
