# Generated by Django 4.2.3 on 2023-08-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0011_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appointments',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='emailid',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
